# Generated by Django 5.0.6 on 2024-05-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryDjango', '0002_alter_dish_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='pic',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
    ]
