# Generated by Django 5.0.6 on 2024-05-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryDjango', '0006_alter_person_pin_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='have_review',
            field=models.BooleanField(default=False),
        ),
    ]
