# Generated by Django 5.0.6 on 2024-05-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryDjango', '0007_order_have_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DeliveryDjango.restaurant'),
        ),
    ]
